# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the current directory contents into the container at /app/
COPY . /app/

# Expose the port that React will run on
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
